# Generated by Django 5.2.4 on 2025-07-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='img',
            field=models.ImageField(default='images/nb.jpg', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
